### ISSUE TITLE
No attribute players_list in the sensor minecraft_server_players_online

### ISSUE THREAD

**Issue by Emeraude998** [cyberjacob/minecraft-home-assistant#3]
Hello, 

I'm using this custom integration as the one from Home Assistant Core doesn't seem to want to connect to my server. 
But I'm facing the following issue. I want to be able to list the players currently connected to my server and I even made a card that should work:
<details>
  <summary>Click for image</summary>

![image](https://user-images.githubusercontent.com/70350808/218346611-079e4406-8d1e-475c-a7c5-63560e2e9a37.png)

</details>

But it seems that there is no attribute corresponding to the players list for the sensor minecraft_server_players_online.

![image](https://user-images.githubusercontent.com/70350808/218346693-43a91759-1b87-4396-9827-948eb205908e.png)

I checked the code in the sensor.py file and there should be one.

Can someone help me?

**Comment by girlpunk** [comment]
Hi,

To my knowledge the built-in integration still has a major flaw in it's design that means a large number of servers on the internet will not be compatible.

I don't really maintain this any more, but having a look through suggests the attribute may not be set if it cannot be retrieved from the server, or if the player list is empty. Could the latter be the case while you're testing?
